### ISSUE TITLE
Release mode produces these errors while debug mode does not

### ISSUE THREAD

**Issue by MichaelWallace30** [gerritv/Xbee-ZigBeeLib#1]
Seems to be some thing wrong with the debug defines, but I don't understand them.

zigbee\zigbee_zdo.c(1108): error C2065: 'resp_t': undeclared identifier
zigbee\zcl_client.c(203): error C2065: 'zdo_rsp_t': undeclared identifier
zigbee\zcl_commissioning.c(621): error C2065: 'zcl_hdr_nomfg_t': undeclared identifier
zigbee\zigbee_zdo.c(275): error C2065: 'request_t': undeclared identifier

**Comment by MichaelWallace30** [comment]
Well it seems the problem is it won't compile in ( C /TC). The debug setting is in (C++ /TP) which works and the release settings is in (C++ /TP) works also. Properties->C/C++->Advanced->Compile As
Does this make this code incompatible with the xbee_ansic_library github resp or does this allow proper alignment of bytes?

**Comment by gerritv** [comment]
Thank you for finding my error, I will update this repository soon.

Interesting oversight on my part, I only ever tried this in Debug version.
Byte alignment and padding is taken care of with the PACK/PACKREVERT pairings. I may have too many of those but better safe than sorry.

The original code was geared to running on small micros. A lot of complexity added to satisfy that cross compile etc. The code is riddled with abuse of C, e.g. indeterminate return values.
I now also have a version that is in C#, much cleaner code as the language forces type correctness. Works fine in .Net Forms apps etc. I will be adding that to my GitHub in the next week.

**Comment by venushkadharmasiri** [comment]
when i'm going to use MSbuild i'm getting following Errors
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL

C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL>MSbuild Xbee-ZigBeeDLL.vcxproj /p:configuration=debug
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/30/2016 3:09:32 PM.
Project "C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL\Xbee-ZigBeeDLL.vcxproj" on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(212,22): error MSB4086: A numeric com
parison was attempted on "$(TargetPlatformVersion)" that evaluates to "10.0.10069.0" instead of a number, in condition
"'$(TargetPlatformIdentifier)' == 'Windows' and '$(TargetPlatformVersion)' > '7.0' and ('@(ClCompile->WithMetadataValue
('CompileAsWinRT', 'true'))@(Midl->WithMetadataValue('EnableWindowsRuntime', 'true'))' != '' or ('@(ClCompile)@(Midl)'
== '' and '$(WindowsAppContainer)' == 'true'))". [C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL\Xbee-ZigBeeDL
L.vcxproj]
Done Building Project "C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL\Xbee-ZigBeeDLL.vcxproj" (default targets
) -- FAILED.


Build FAILED.

"C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL\Xbee-ZigBeeDLL.vcxproj" (default target) (1) ->
(_PrepareForReferenceResolution target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(212,22): error MSB4086: A numeric c
omparison was attempted on "$(TargetPlatformVersion)" that evaluates to "10.0.10069.0" instead of a number, in conditio
n "'$(TargetPlatformIdentifier)' == 'Windows' and '$(TargetPlatformVersion)' > '7.0' and ('@(ClCompile->WithMetadataVal
ue('CompileAsWinRT', 'true'))@(Midl->WithMetadataValue('EnableWindowsRuntime', 'true'))' != '' or ('@(ClCompile)@(Midl)
' == '' and '$(WindowsAppContainer)' == 'true'))". [C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL\Xbee-ZigBee
DLL.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.69

C:\Users\venushka\Desktop\Xbee-ZigBeeLib\Xbee-ZigBeeDLL>

**Comment by gerritv** [comment]
@venushkadharmasiri I created a new issue for you and answered. See Issue 2
